In [2]:
import torch

In [3]:
torch.__version__

'2.9.1'

 MPS (Metal Performance Shaders)

In [4]:

if torch.backends.mps.is_available():
    print("MPS available:", torch.backends.mps.is_built())
    print("MPS name:", torch.backends.mps.get_name())
    print("MPS name:", torch.backends.mps.get_core_count())
else:
    print("MPS not available")


MPS available: True
MPS name: Apple M3
MPS name: 8


------

## Tensor

In [5]:
torch.empty(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
a=torch.empty(2,3)

In [7]:
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
type(a)

torch.Tensor

In [9]:
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
torch.ones(2,4)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
torch.rand(2,4)


tensor([[0.7100, 0.6907, 0.0786, 0.8041],
        [0.4417, 0.2618, 0.7019, 0.5660]])

In [12]:
torch.rand(2,4)


tensor([[0.8759, 0.7326, 0.0143, 0.1284],
        [0.4018, 0.3942, 0.4735, 0.8687]])

In [13]:
# use of seed 

torch.manual_seed(100)
torch.rand(2,4)




tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428]])

In [14]:
torch.manual_seed(100)
torch.rand(2,4)


tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428]])

In [15]:
a1 =torch.tensor([[4,3,2],[1,2,3]])
a1

tensor([[4, 3, 2],
        [1, 2, 3]])

In [16]:
type(a1)

torch.Tensor

In [17]:
print(torch.arange(5,15,2))

print(torch.linspace(5,25,2))

print(torch.eye(5,4))

print(torch.full((5,4),7))

tensor([ 5,  7,  9, 11, 13])
tensor([ 5., 25.])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])
tensor([[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]])


In [18]:
a1

tensor([[4, 3, 2],
        [1, 2, 3]])

In [19]:
a1.shape

torch.Size([2, 3])

In [20]:
# create tensor with similar shape

torch.empty_like(a1)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [28]:
a1

tensor([[4, 3, 2],
        [1, 2, 3]])

In [21]:
torch.rand_like(a1)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [32]:
a1.dtype

torch.int64

In [34]:
torch.rand_like(a1,dtype=torch.float16)

tensor([[0.7568, 0.3916, 0.4927],
        [0.3672, 0.1367, 0.8198]], dtype=torch.float16)

In [ ]:
#a1 contains int and rand generates float type

In [ ]:
torch.rand(2,3)

tensor([[0.4183, 0.9014, 0.9969],
        [0.7565, 0.2239, 0.3023]])

-----

Tensor Data Types

In [22]:
a1.dtype

torch.int64

In [24]:
torch.tensor([[1.3,2.0,6.0],[1.2,9.0,7.0]],dtype=torch.int32)

tensor([[1, 2, 6],
        [1, 9, 7]], dtype=torch.int32)

In [25]:
a1

tensor([[4, 3, 2],
        [1, 2, 3]])

In [26]:
a1.to(torch.float32)

tensor([[4., 3., 2.],
        [1., 2., 3.]])

| PyTorch dtype                    | Description                       | Typical use cases                                                                                        |
| -------------------------------- | --------------------------------- | -------------------------------------------------------------------------------------------------------- |
| `torch.float32` (`torch.float`)  | 32-bit floating point             | Default for most ML/DL models. Training neural networks, general numeric computation.                    |
| `torch.float64` (`torch.double`) | 64-bit floating point             | High-precision math, scientific computing, debugging numerical stability issues. Slower.                 |
| `torch.float16` (`torch.half`)   | 16-bit floating point             | Mixed-precision training on GPUs with Tensor Cores. Reduces memory and speeds up training. Not for CPUs. |
| `torch.bfloat16`                 | 16-bit float with larger exponent | TPUs/Ampere+ GPUs. More stable than fp16, good for mixed precision.                                      |
| `torch.int64` (`torch.long`)     | 64-bit integer                    | **Indices**, **class labels** in classification tasks, embeddings index.                                 |
| `torch.int32` (`torch.int`)      | 32-bit integer                    | Numeric operations requiring integers but not for indices typically.                                     |
| `torch.int16` (`torch.short`)    | 16-bit integer                    | Rarely used, small integer tensors.                                                                      |
| `torch.int8`                     | 8-bit integer                     | Quantized models, memory-efficient storage.                                                              |
| `torch.uint8`                    | Unsigned 8-bit integer            | Images (0–255), masks, binary flags.                                                                     |
| `torch.bool`                     | Boolean                           | Masks, attention masks, condition filtering.                                                             |
| `torch.complex64`                | Complex numbers (2×32-bit floats) | Fourier transforms, signal processing, physics simulations.                                              |
| `torch.complex128`               | Higher precision complex          | High-precision scientific computations.                                                                  |


------

mathmatical operations

In [38]:
b1=torch.rand(3,4)
print(b1)
print(b1.dtype)

tensor([[0.1784, 0.8238, 0.5557, 0.9770],
        [0.4440, 0.9478, 0.7445, 0.4892],
        [0.2426, 0.7003, 0.5277, 0.2472]])
torch.float32


In [39]:
b1+2

tensor([[2.1784, 2.8238, 2.5557, 2.9770],
        [2.4440, 2.9478, 2.7445, 2.4892],
        [2.2426, 2.7003, 2.5277, 2.2472]])

In [40]:
b1-2

tensor([[-1.8216, -1.1762, -1.4443, -1.0230],
        [-1.5560, -1.0522, -1.2555, -1.5108],
        [-1.7574, -1.2997, -1.4723, -1.7528]])

In [41]:
b1*10

tensor([[1.7842, 8.2384, 5.5574, 9.7702],
        [4.4402, 9.4785, 7.4448, 4.8920],
        [2.4256, 7.0034, 5.2769, 2.4718]])

In [42]:
b1/10

tensor([[0.0178, 0.0824, 0.0556, 0.0977],
        [0.0444, 0.0948, 0.0744, 0.0489],
        [0.0243, 0.0700, 0.0528, 0.0247]])

In [68]:
b1=torch.rand(3,4)
c1=torch.rand(3,4)
print(b1)
print(c1)

tensor([[0.9140, 0.0085, 0.2174, 0.1890],
        [0.0911, 0.6344, 0.3142, 0.7052],
        [0.6447, 0.9517, 0.3581, 0.3411]])
tensor([[0.0433, 0.4373, 0.9947, 0.1748],
        [0.1374, 0.8005, 0.7004, 0.8803],
        [0.1573, 0.3343, 0.9652, 0.1862]])


In [69]:
b1+c1,"---",0.7909+0.3182   # each element wise

(tensor([[0.9573, 0.4459, 1.2121, 0.3638],
         [0.2285, 1.4349, 1.0145, 1.5855],
         [0.8020, 1.2860, 1.3234, 0.5273]]),
 '---',
 1.1091)

In [70]:
b1*c1

tensor([[0.0396, 0.0037, 0.2162, 0.0330],
        [0.0125, 0.5078, 0.2200, 0.6208],
        [0.1014, 0.3181, 0.3457, 0.0635]])

In [71]:
torch.round(c1)

tensor([[0., 0., 1., 0.],
        [0., 1., 1., 1.],
        [0., 0., 1., 0.]])

In [72]:
c1

tensor([[0.0433, 0.4373, 0.9947, 0.1748],
        [0.1374, 0.8005, 0.7004, 0.8803],
        [0.1573, 0.3343, 0.9652, 0.1862]])

In [73]:
# define range --clamp

torch.clamp(c1,max=0.5,min=0)

tensor([[0.0433, 0.4373, 0.5000, 0.1748],
        [0.1374, 0.5000, 0.5000, 0.5000],
        [0.1573, 0.3343, 0.5000, 0.1862]])

In [85]:
b1=torch.randint(size=(3,4),low=1,high=5)
c1=torch.randint(size=(4,5),low=1,high=50,dtype=float)
print(b1)
print(c1)

tensor([[3, 1, 3, 1],
        [2, 2, 2, 3],
        [3, 1, 3, 2]])
tensor([[37., 27., 41., 26., 32.],
        [22.,  9.,  5., 30., 32.],
        [20.,  3., 13., 13., 38.],
        [ 9., 31., 26.,  7., 34.]], dtype=torch.float64)


In [86]:
torch.sum(b1) # sum of all element of c1

tensor(26)

In [87]:
torch.mean(c1)

tensor(22.7500, dtype=torch.float64)

In [91]:
# matmultiplication

In [92]:
b1=b1.to(dtype=float)
torch.matmul(b1,c1)

tensor([[202., 130., 193., 154., 276.],
        [185., 171., 196., 159., 306.],
        [211., 161., 219., 161., 310.]], dtype=torch.float64)

In [98]:
b1=torch.randint(size=(3,4),low=1,high=5,dtype=float)
c1=torch.randint(size=(3,4),low=1,high=50,dtype=float)
print(b1)
print(c1)

tensor([[1., 4., 3., 4.],
        [1., 1., 1., 2.],
        [4., 4., 2., 2.]], dtype=torch.float64)
tensor([[24., 43., 19.,  3.],
        [26.,  2., 19.,  3.],
        [14., 37., 22., 14.]], dtype=torch.float64)


In [101]:
b1.add(c1),"---",b1,"---",c1

(tensor([[49., 90., 41., 10.],
         [53.,  5., 39.,  8.],
         [32., 78., 46., 30.]], dtype=torch.float64),
 '---',
 tensor([[25., 47., 22.,  7.],
         [27.,  3., 20.,  5.],
         [18., 41., 24., 16.]], dtype=torch.float64),
 '---',
 tensor([[24., 43., 19.,  3.],
         [26.,  2., 19.,  3.],
         [14., 37., 22., 14.]], dtype=torch.float64))

-----

In [ ]:
b1.add_(c1),"---",b1,"---",c1      # perform operation and store in same variable

(tensor([[49., 90., 41., 10.],
         [53.,  5., 39.,  8.],
         [32., 78., 46., 30.]], dtype=torch.float64),
 '---',
 tensor([[49., 90., 41., 10.],
         [53.,  5., 39.,  8.],
         [32., 78., 46., 30.]], dtype=torch.float64),
 '---',
 tensor([[24., 43., 19.,  3.],
         [26.,  2., 19.,  3.],
         [14., 37., 22., 14.]], dtype=torch.float64))

In [103]:
b1

tensor([[49., 90., 41., 10.],
        [53.,  5., 39.,  8.],
        [32., 78., 46., 30.]], dtype=torch.float64)

In [106]:
b1.relu_()

tensor([[49., 90., 41., 10.],
        [53.,  5., 39.,  8.],
        [32., 78., 46., 30.]], dtype=torch.float64)

# on Gpu / MPS

In [1]:
import torch
torch.backends.mps.is_available()


True

In [2]:
device = torch.device("mps")  # mac GPU
x = torch.tensor([1, 2, 3], device=device)
print(x, x.device)

tensor([1, 2, 3], device='mps:0') mps:0


In [3]:
# move cpu tensor to mps 

cpu_tensor = torch.randn(4, 4)
gpu_tensor = cpu_tensor.to("mps")


In [4]:
gpu_tensor

tensor([[-1.0106,  0.5428,  0.1132, -0.1408],
        [-0.8971,  0.2375, -1.1706,  2.1225],
        [-1.5718,  1.7827, -0.2502, -0.8807],
        [ 0.3407,  1.1218, -0.2638, -1.5237]], device='mps:0')